#
# GNUmakefile - Generated by ProjectCenter
#
ifeq ($(shell uname -s),Darwin)
.DEFAULT_GOAL := all
.PHONY: all clean run release test test-plugins
all clean run release test test-plugins:
	$(MAKE) -f Makefile $@
else
ifeq ($(GNUSTEP_MAKEFILES),)
 GNUSTEP_MAKEFILES := $(shell gnustep-config --variable=GNUSTEP_MAKEFILES 2>/dev/null)
  ifeq ($(GNUSTEP_MAKEFILES),)
    $(warning )
    $(warning Unable to obtain GNUSTEP_MAKEFILES setting from gnustep-config!)
    $(warning Perhaps gnustep-make is not properly installed,)
    $(warning so gnustep-config is not in your PATH.)
    $(warning )
    $(warning Your PATH is currently $(PATH))
    $(warning )
  endif
endif
ifeq ($(GNUSTEP_MAKEFILES),)
 $(error You need to set GNUSTEP_MAKEFILES before compiling!)
endif

include $(GNUSTEP_MAKEFILES)/common.make
.DEFAULT_GOAL := all

#
# Application
#
VERSION = 0.1
PACKAGE_NAME = ScoreMaker
APP_NAME = ScoreMaker
ScoreMaker_APPLICATION_ICON = Resources/ScoreMakerAppIcon.png


#
# Resource files
#
ScoreMaker_RESOURCE_FILES = \
Resources/bass_clef.png \
Resources/ScoreMakerAppIcon.png \
Resources/ScoreMakerDocumentIcon.png \
Resources/treble_clef.png \
Resources/README.md \
Resources/ChangeLog \
Resources/LICENSE \
Resources/ScoreMakerAppIcon.icns \
Resources/ScoreMakerDocumentIcon.icns 


#
# Header files
#
ScoreMaker_HEADER_FILES = \
src/RealtimeDSP.h \
src/AppDelegate.h \
src/ScoreMakerDocumentController.h \
src/ScoreMakerDocument.h \
src/MidiParser.h \
src/MusicXMLParser.h \
src/ScorefileParser.h \
src/ScoreProjectSerializer.h \
src/ScoreModel.h \
src/MusicPlatformModel.h \
src/MusicEngine.h \
src/NotationModel.h \
src/EngravingLayout.h \
src/ScoreView.h \
src/PlaybackMonitorView.h \
src/MIDIInputManager.h

#
# Objective-C Class files
#
ScoreMaker_OBJC_FILES = \
src/RealtimeDSP.m \
src/main.m \
src/AppDelegate.m \
src/ScoreMakerDocumentController.m \
src/ScoreMakerDocument.m \
src/MidiParser.m \
src/MusicXMLParser.m \
src/ScorefileParser.m \
src/ScoreProjectSerializer.m \
src/ScoreModel.m \
src/MusicPlatformModel.m \
src/MusicEngine.m \
src/NotationModel.m \
src/EngravingLayout.m \
src/ScoreView.m \
src/PlaybackMonitorView.m \
src/MIDIInputManager.m

.PHONY: test
test: all
	mkdir -p build/tests
	clang $$(gnustep-config --objc-flags) -Wall -Wextra -fobjc-exceptions -Isrc tests/ScorefileCompatibilityTests.m src/RealtimeDSP.m src/ScorefileParser.m src/ScoreProjectSerializer.m src/MusicXMLParser.m src/MidiParser.m src/ScoreModel.m src/MusicPlatformModel.m src/MusicEngine.m src/NotationModel.m src/EngravingLayout.m $$(gnustep-config --gui-libs) -lAVFoundation -o build/tests/scorefile-tests
	build/tests/scorefile-tests

#
# Makefiles
#
-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/aggregate.make
include $(GNUSTEP_MAKEFILES)/application.make
-include GNUmakefile.postamble
endif

.PHONY: documentation
documentation:
	$(MAKE) -C Documentation -f GNUmakefile
